name: Deploy Node Application

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  REPOSITORY: mail-manager-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEVOPS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEVOPS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEVOPS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEVOPS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Blue-Green Deploy API
        env:
          IMAGE_TAG: latest
        run: |
          set -e

          IMAGE="$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG"
          ENV_FILE="/etc/mail-manager/api.env"
          NGINX_UPSTREAM="/etc/nginx/conf.d/mdnac-api-upstream.conf"

          echo "Pulling image..."
          docker pull $IMAGE

          echo "Starting NEW container on port 3002..."
          docker run -d \
            --name mail-manager-api-new \
            -p 3002:4000 \
             --memory="600m" \
            --cpus="0.75" \
            -e DATABASE_URL='${{secrets.DATABASE_URL}}' -e JWT_SECRET='${{secrets.JWT_SECRET}}' -e AWS_REGION='${{secrets.AWS_REGION}}' -e AWS_ACCESS_KEY='${{secrets.AWS_ACCESS_KEY}}' -e AWS_SECRET_KEY='${{secrets.AWS_SECRET_KEY}}' -e AWS_S3_BUCKET='${{secrets.AWS_S3_BUCKET}}' \
            --restart unless-stopped \
            $IMAGE

          echo "Waiting for API to be ready..."
          sleep 10

          echo "Switching Nginx traffic to new container..."
          sudo sed -i 's/3001/3002/g' $NGINX_UPSTREAM
          sudo nginx -t
          sudo systemctl reload nginx

          echo "Stopping OLD container..."
          docker stop mail-manager-api-container || true
          docker rm mail-manager-api-container || true

          echo "Renaming NEW container..."
          docker rename mail-manager-api-new mail-manager-api-container

          echo "Deployment completed successfully ðŸš€"