name: Doploy Node Application

on:
  push:
    branches:
      - aws-add

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t artisg/mail-manager-api .

      - name: Publish Image to docker hub
        run: docker push artisg/mail-manager-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Pull image from docker hub
        run: docker pull artisg/mail-manager-api:latest
      - name: Run docker Container
        run: docker run -d -p 4000:4000 --name mail-manager-api-container -e DATABASE_URL='${{secrets.DATABASE_URL}}' -e JWT_SECRET='${{secrets.JWT_SECRET}}' -e AWS_REGION='${{secrets.AWS_REGION}}' -e AWS_ACCESS_KEY='${{secrets.AWS_ACCESS_KEY}}' -e AWS_SECRET_KEY='${{secrets.AWS_SECRET_KEY}}' -e AWS_S3_BUCKET='${{secrets.AWS_S3_BUCKET}}'
